package com.automasters.util;

import com.automasters.entity.Invoice;
import com.automasters.entity.InvoiceItem;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import java.awt.Color;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class PDFReportGenerator {

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 18, Font.BOLD, new Color(30, 41, 59));
    private static final Font SUBTITLE_FONT = new Font(Font.HELVETICA, 12, Font.NORMAL, Color.GRAY);
    private static final Font HEADER_FONT = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);
    private static final Font CELL_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL, Color.BLACK);
    private static final Color HEADER_BG_COLOR = new Color(59, 130, 246);

    public static void generateDailyReport(List<Invoice> invoices, LocalDate date, String filePath) throws IOException {
        Document document = new Document(PageSize.A4);
        try {
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();

            // Header
            addHeader(document, date);

            // Summary Table
            addSummaryTable(document, invoices);

            // Invoice List Table
            addInvoiceTable(document, invoices);

            // Footer
            addFooter(document);

        } catch (DocumentException e) {
            throw new IOException("Error generating PDF report", e);
        } finally {
            document.close();
        }
    }

    private static void addHeader(Document document, LocalDate date) throws DocumentException {
        Paragraph title = new Paragraph("Daily Invoice Report", TITLE_FONT);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        String dateStr = date.format(DateTimeFormatter.ofPattern("MMMM dd, yyyy"));
        Paragraph subtitle = new Paragraph("Date: " + dateStr, SUBTITLE_FONT);
        subtitle.setAlignment(Element.ALIGN_CENTER);
        subtitle.setSpacingAfter(20);
        document.add(subtitle);
    }

    private static void addSummaryTable(Document document, List<Invoice> invoices) throws DocumentException {
        double totalIncome = invoices.stream().mapToDouble(Invoice::getTotalAmount).sum();
        int totalInvoices = invoices.size();

        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(50);
        table.setSpacingAfter(20);

        table.addCell(createCell("Total Invoices:", true));
        table.addCell(createCell(String.valueOf(totalInvoices), false));
        table.addCell(createCell("Total Income:", true));
        table.addCell(createCell(String.format("LKR %.2f", totalIncome), false));

        document.add(table);
    }

    private static void addInvoiceTable(Document document, List<Invoice> invoices) throws DocumentException {
        PdfPTable table = new PdfPTable(5); // Num, Customer, Vehicle, Items, Amount
        table.setWidthPercentage(100);
        table.setWidths(new float[] { 2, 3, 2, 4, 2 });
        table.setSpacingBefore(10);

        // Headers
        String[] headers = { "Invoice #", "Customer", "Vehicle", "Services", "Amount" };
        for (String header : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(header, HEADER_FONT));
            cell.setBackgroundColor(HEADER_BG_COLOR);
            cell.setPadding(6);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell(cell);
        }

        // Data
        for (Invoice invoice : invoices) {
            table.addCell(createCell(invoice.getInvoiceNumber(), false));
            table.addCell(createCell(invoice.getCustomerName(), false));
            table.addCell(createCell(invoice.getVehicleNumber(), false));

            // Summarize items
            StringBuilder itemsStr = new StringBuilder();
            List<InvoiceItem> items = invoice.getItems();
            if (items != null && !items.isEmpty()) {
                itemsStr.append(items.get(0).getDescription());
                if (items.size() > 1) {
                    itemsStr.append(" (+").append(items.size() - 1).append(" more)");
                }
            }
            table.addCell(createCell(itemsStr.toString(), false));

            PdfPCell amountCell = createCell(String.format("%.2f", invoice.getTotalAmount()), false);
            amountCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            table.addCell(amountCell);
        }

        document.add(table);
    }

    private static void addFooter(Document document) throws DocumentException {
        Paragraph footer = new Paragraph("Generated by GalleAuto Service Billing System",
                new Font(Font.HELVETICA, 8, Font.ITALIC, Color.GRAY));
        footer.setAlignment(Element.ALIGN_CENTER);
        footer.setSpacingBefore(30);
        document.add(footer);
    }

    private static PdfPCell createCell(String content, boolean isHeader) {
        PdfPCell cell = new PdfPCell(new Phrase(content,
                isHeader ? new Font(CELL_FONT.getFamily(), CELL_FONT.getSize(), Font.BOLD) : CELL_FONT));
        cell.setPadding(5);
        if (isHeader) {
            cell.setBackgroundColor(new Color(240, 240, 240));
        }
        return cell;
    }
}
